### ISSUE TITLE
support AT

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-cli#72]
[^ goto parent epic](https://github.com/adaptlearning/adapt-cli/issues/74)

general epic for tickets about supporting plugin dependencies and moving AT plugin management backward into the adapt-cli
give foundation for AT
* output in json format for parsing by AT
* support this kinda idea https://github.com/adaptlearning/adapt_authoring/issues/921

**Comment by taylortom** [comment]
If possible, we'd like to be able to consume this as an imported module, rather than having to use something like [child_process.exec](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) to run the CLI in a spawned shell, which is what we've done in the past.

It'd be nice to just be able to do things like: `cli.cloneFramework(...)`

**Comment by oliverfoster** [comment]
that's a good idea
